@extends('layouts.app')

@section('title', 'Reports - Admin')

@section('content')
<div class="mb-4">
    <h2 class="fw-bold" style="color: #1e3c72;"><i class="fas fa-chart-bar"></i> Reports & Analytics</h2>
    <p class="text-muted">Generate and view system reports</p>
</div>

<!-- Report Type Selection -->
<div class="row g-4 mb-4">
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center">
                <div class="mb-3">
                    <i class="fas fa-users fa-3x" style="color: #1e3c72;"></i>
                </div>
                <h5 class="card-title">User Report</h5>
                <p class="card-text text-muted">Generate detailed user statistics and activity reports</p>
                <button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#userReportModal">
                    <i class="fas fa-file-download"></i> Generate Report
                </button>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center">
                <div class="mb-3">
                    <i class="fas fa-clipboard-list fa-3x" style="color: #56ab2f;"></i>
                </div>
                <h5 class="card-title">Program Report</h5>
                <p class="card-text text-muted">View program performance and participation metrics</p>
                <button class="btn btn-success" data-bs-toggle="modal" data-bs-target="#programReportModal">
                    <i class="fas fa-file-download"></i> Generate Report
                </button>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card h-100">
            <div class="card-body text-center">
                <div class="mb-3">
                    <i class="fas fa-chart-line fa-3x" style="color: #f2994a;"></i>
                </div>
                <h5 class="card-title">Activity Report</h5>
                <p class="card-text text-muted">Track system activities and audit trail data</p>
                <button class="btn btn-warning" data-bs-toggle="modal" data-bs-target="#activityReportModal">
                    <i class="fas fa-file-download"></i> Generate Report
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Quick Statistics -->
<div class="row g-4 mb-4">
    <div class="col-xl-3 col-md-6">
        <div class="stat-card">
            <div class="stat-card-icon primary">
                <i class="fas fa-users"></i>
            </div>
            <div class="stat-card-content">
                <div class="stat-card-value">{{ $userStats['total'] ?? 0 }}</div>
                <div class="stat-card-label">Total Users</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="stat-card">
            <div class="stat-card-icon success">
                <i class="fas fa-user-plus"></i>
            </div>
            <div class="stat-card-content">
                <div class="stat-card-value">{{ $userStats['thisMonth'] ?? 0 }}</div>
                <div class="stat-card-label">New Users This Month</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="stat-card">
            <div class="stat-card-icon warning">
                <i class="fas fa-clipboard-check"></i>
            </div>
            <div class="stat-card-content">
                <div class="stat-card-value">{{ $programStats['completed'] ?? 0 }}</div>
                <div class="stat-card-label">Completed Programs</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6">
        <div class="stat-card">
            <div class="stat-card-icon info">
                <i class="fas fa-percentage"></i>
            </div>
            <div class="stat-card-content">
                <div class="stat-card-value">{{ $programStats['completionRate'] ?? 0 }}%</div>
                <div class="stat-card-label">Completion Rate</div>
            </div>
        </div>
    </div>
</div>

<!-- Recent Generated Reports -->
<div class="card">
    <div class="card-header">
        <h5 class="mb-0"><i class="fas fa-file-alt"></i> Recent Generated Reports</h5>
    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Report Type</th>
                        <th>Date Range</th>
                        <th>Format</th>
                        <th>Generated By</th>
                        <th>Generated At</th>
                        <th>Filename</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($recentReports as $report)
                    <tr>
                        <td>
                            <span class="badge" style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%);">
                                {{ $report->report_type }}
                            </span>
                        </td>
                        <td>{{ ucfirst(str_replace('_', ' ', $report->date_range)) }}</td>
                        <td>
                            @if($report->format == 'PDF')
                            <span class="badge bg-danger">{{ $report->format }}</span>
                            @elseif($report->format == 'EXCEL')
                            <span class="badge bg-success">{{ $report->format }}</span>
                            @else
                            <span class="badge bg-info">{{ $report->format }}</span>
                            @endif
                        </td>
                        <td>{{ $report->user->name ?? 'N/A' }}</td>
                        <td>{{ $report->created_at->format('M d, Y H:i') }}</td>
                        <td><code class="small">{{ $report->filename }}</code></td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="6" class="text-center py-5">
                            <i class="fas fa-file-alt fa-3x text-muted mb-3"></i>
                            <p class="text-muted mb-0">No reports generated yet. Create your first report using the options above.</p>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- User Report Modal -->
<div class="modal fade" id="userReportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background: linear-gradient(135deg, #1e3c72 0%, #2a5298 100%); color: white;">
                <h5 class="modal-title">Generate User Report</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST" action="{{ route('admin.reports.generate') }}">
                @csrf
                <input type="hidden" name="report_type" value="user">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Date Range</label>
                        <select name="date_range" class="form-select" required>
                            <option value="last_7_days">Last 7 Days</option>
                            <option value="last_30_days">Last 30 Days</option>
                            <option value="last_3_months">Last 3 Months</option>
                            <option value="last_year">Last Year</option>
                            <option value="all_time">All Time</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">User Role</label>
                        <select name="role" class="form-select">
                            <option value="all">All Roles</option>
                            <option value="admin">Admin</option>
                            <option value="coordinator">Coordinator</option>
                            <option value="participant">Participant</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Format</label>
                        <select name="format" class="form-select" required>
                            <option value="pdf">PDF</option>
                            <option value="excel">Excel</option>
                            <option value="csv">CSV</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-primary">
                        <i class="fas fa-download"></i> Generate & Download
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Program Report Modal -->
<div class="modal fade" id="programReportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background: linear-gradient(135deg, #56ab2f 0%, #a8e063 100%); color: white;">
                <h5 class="modal-title">Generate Program Report</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST" action="{{ route('admin.reports.generate') }}">
                @csrf
                <input type="hidden" name="report_type" value="program">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Date Range</label>
                        <select name="date_range" class="form-select" required>
                            <option value="last_7_days">Last 7 Days</option>
                            <option value="last_30_days">Last 30 Days</option>
                            <option value="last_3_months">Last 3 Months</option>
                            <option value="last_year">Last Year</option>
                            <option value="all_time">All Time</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Program Status</label>
                        <select name="status" class="form-select">
                            <option value="all">All Statuses</option>
                            <option value="active">Active</option>
                            <option value="upcoming">Upcoming</option>
                            <option value="completed">Completed</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Category</label>
                        <select name="category" class="form-select">
                            <option value="all">All Categories</option>
                            <option value="fitness">Fitness</option>
                            <option value="nutrition">Nutrition</option>
                            <option value="mental_health">Mental Health</option>
                            <option value="wellness">Wellness</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Format</label>
                        <select name="format" class="form-select" required>
                            <option value="pdf">PDF</option>
                            <option value="excel">Excel</option>
                            <option value="csv">CSV</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-success">
                        <i class="fas fa-download"></i> Generate & Download
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>

<!-- Activity Report Modal -->
<div class="modal fade" id="activityReportModal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background: linear-gradient(135deg, #f2994a 0%, #f2c94c 100%); color: white;">
                <h5 class="modal-title">Generate Activity Report</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal"></button>
            </div>
            <form method="POST" action="{{ route('admin.reports.generate') }}">
                @csrf
                <input type="hidden" name="report_type" value="activity">
                <div class="modal-body">
                    <div class="mb-3">
                        <label class="form-label">Date Range</label>
                        <select name="date_range" class="form-select" required>
                            <option value="last_7_days">Last 7 Days</option>
                            <option value="last_30_days">Last 30 Days</option>
                            <option value="last_3_months">Last 3 Months</option>
                            <option value="last_year">Last Year</option>
                            <option value="all_time">All Time</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Action Type</label>
                        <select name="action" class="form-select">
                            <option value="all">All Actions</option>
                            <option value="create">Create</option>
                            <option value="update">Update</option>
                            <option value="delete">Delete</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Model</label>
                        <select name="model" class="form-select">
                            <option value="all">All Models</option>
                            <option value="User">User</option>
                            <option value="Program">Program</option>
                            <option value="Registration">Registration</option>
                            <option value="Session">Session</option>
                        </select>
                    </div>
                    <div class="mb-3">
                        <label class="form-label">Format</label>
                        <select name="format" class="form-select" required>
                            <option value="pdf">PDF</option>
                            <option value="excel">Excel</option>
                            <option value="csv">CSV</option>
                        </select>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    <button type="submit" class="btn btn-warning text-white">
                        <i class="fas fa-download"></i> Generate & Download
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection
